set(TOOLCHAIN_DIR "" CACHE STRING "")
set(TARGET_TRIPLE "" CACHE STRING "")

set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(LLVM_BUILD_STATIC ON CACHE BOOL "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")

set(CMAKE_SYSTEM_NAME Linux CACHE BOOL "")
set(LLVM_DEFAULT_TARGET_TRIPLE ${TARGET_TRIPLE} CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET ${TARGET_TRIPLE} CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET ${TARGET_TRIPLE} CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE} CACHE STRING "")

set(CMAKE_C_COMPILER "${TOOLCHAIN_DIR}/bin/clang" CACHE STRING "")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/bin/clang++" CACHE STRING "")
set(CMAKE_RANLIB "${TOOLCHAIN_DIR}/bin/llvm-ranlib" CACHE STRING "")
set(CMAKE_AR "${TOOLCHAIN_DIR}/bin/llvm-ar" CACHE STRING "")
set(LLVM_ENABLE_LLD ON CACHE BOOL "")

set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "")

set(LLVM_ENABLE_RUNTIMES "libcxx;libcxxabi;libunwind" CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY CACHE STRING "")

set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBUNWIND_INSTALL_LIBRARY OFF CACHE BOOL "")
set(LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")

set(LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
set(LIBCXXABI_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
set(LIBCXXABI_INSTALL_LIBRARY OFF CACHE BOOL "")
set(LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")

set(LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
set(LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
set(LIBCXX_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
set(LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
