set(SYSROOTS_DIR "" CACHE STRING "")
set(LLVM_TARGETS "" CACHE STRING "")
set(LLVM_TRIPLES "" CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD "Native;${LLVM_TARGETS}" CACHE STRING "")
set(toolchain_targets "default;${LLVM_TRIPLES}")

set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")

set(LLVM_ENABLE_DIA_SDK OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBEDIT OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")
set(LLVM_ENABLE_TERMINFO OFF CACHE BOOL "")
set(LLVM_ENABLE_UNWIND_TABLES OFF CACHE BOOL "")
set(LLVM_ENABLE_Z3_SOLVER OFF CACHE BOOL "")
set(LLVM_ENABLE_ZLIB OFF CACHE BOOL "")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(LLVM_INSTALL_TOOLCHAIN_ONLY ON CACHE BOOL "")
set(LLVM_HAVE_LIBXAR OFF CACHE BOOL "")

set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "")

set(LLVM_ENABLE_PROJECTS "llvm;clang;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "")

set(LLVM_BUILTIN_TARGETS ${toolchain_targets} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${toolchain_targets} CACHE STRING "")

foreach(target ${toolchain_targets})
    if(${target} STREQUAL "default")
        continue()
    endif()
    string(REPLACE "-" ";" target_parts ${target})
    list(GET target_parts 0 target_arch)

    set(BUILTINS_${target}_CMAKE_SYSTEM_NAME "Linux" CACHE STRING "")
    set(BUILTINS_${target}_CMAKE_BUILD_TYPE "Release" CACHE STRING "")
    set(BUILTINS_${target}_CMAKE_SYSROOT "${SYSROOTS_DIR}/${target_arch}" CACHE STRING "")
    set(BUILTINS_${target}_CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY" CACHE STRING "")

    set(RUNTIMES_${target}_CMAKE_SYSTEM_NAME "Linux" CACHE STRING "")
    set(RUNTIMES_${target}_CMAKE_BUILD_TYPE "Release" CACHE STRING "")
    set(RUNTIMES_${target}_CMAKE_SYSROOT "${SYSROOTS_DIR}/${target_arch}" CACHE STRING "")
    set(RUNTIMES_${target}_CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY" CACHE STRING "")

    set(RUNTIMES_${target}_COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_BUILD_MEMPROF OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_BUILD_ORC OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_STATIC_CXX_LIBRARY ON CACHE BOOL "")
    set(RUNTIMES_${target}_COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXXABI_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXX_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
    set(RUNTIMES_${target}_LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
    set(RUNTIMES_${target}_LIBUNWIND_INSTALL_LIBRARY OFF CACHE BOOL "")
    set(RUNTIMES_${target}_LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")
endforeach()

set(LLVM_ENABLE_LLD ON CACHE BOOL "")
set(LLVM_ENABLE_LIBCXX ON CACHE BOOL "")

set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
set(CLANG_DEFAULT_OBJCOPY llvm-objcopy CACHE STRING "")
set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
set(CLANG_DEFAULT_CXX_STDLIB libc++ CACHE STRING "")
set(CLANG_DEFAULT_UNWINDLIB none CACHE STRING "")
set(CLANG_DEFAULT_PIE_ON_LINUX ON CACHE BOOL "")

set(
    LLVM_DISTRIBUTION_COMPONENTS

    clang
    lld

    llvm-ar
    llvm-nm
    llvm-objcopy
    llvm-objdump
    llvm-ranlib
    llvm-readobj
    llvm-strings
    llvm-strip

    clang-resource-headers
    builtins
    runtimes

    CACHE STRING ""
)

set(CLANG_ENABLE_BOOTSTRAP ON CACHE BOOL "")
set(
    CLANG_BOOTSTRAP_PASSTHROUGH

    LLVM_ENABLE_DIA_SDK
    LLVM_ENABLE_LIBEDIT
    LLVM_ENABLE_LIBXML2
    LLVM_ENABLE_PER_TARGET_RUNTIME_DIR
    LLVM_ENABLE_TERMINFO
    LLVM_ENABLE_UNWIND_TABLES
    LLVM_ENABLE_Z3_SOLVER
    LLVM_ENABLE_ZLIB
    LLVM_INCLUDE_DOCS
    LLVM_INCLUDE_EXAMPLES
    LLVM_INCLUDE_TESTS
    LLVM_INSTALL_TOOLCHAIN_ONLY
    LLVM_HAVE_LIBXAR

    LLVM_ENABLE_LLD
    LLVM_ENABLE_LIBCXX

    CMAKE_POSITION_INDEPENDENT_CODE
    CMAKE_INSTALL_PREFIX
    LLVM_INCLUDE_TESTS
    LLVM_INSTALL_TOOLCHAIN_ONLY
    LLVM_TARGETS_TO_BUILD

    CLANG_DEFAULT_LINKER
    CLANG_DEFAULT_OBJCOPY
    CLANG_DEFAULT_RTLIB
    CLANG_DEFAULT_CXX_STDLIB
    CLANG_DEFAULT_UNWINDLIB
    CLANG_DEFAULT_PIE_ON_LINUX

    LLVM_DISTRIBUTION_COMPONENTS

    CACHE STRING ""
)
